### ISSUE TITLE
New entries in R26 for MENSOR and QUARTZDYNE

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/R26#2]
@nvs-vocabs/reference-tables

I have added the following codes in[ R26](http://vocab.nerc.ac.uk/search_nvs/R26/?searchstr=&options=identifier,preflabel,altlabel,status_accepted&rbaddfilter=inc&searchstr2=) (please note it takes ~24h for them to show up on the VNS).

MENSOR - A manufacturing company located in San Marcos, Texas (United States of America), specialised in precision pressure products.
QUARTZDYNE	- A ChampionX company specialised in resonating quartz pressure transducers and temperature gauges, located in Salt Lake City, Utah (United States of America).

I did so in order to be able to map R27 sensor models 'MENSOR' and 'QUARTZDYNE_DSB301-10-C85' to the correct manufacturer from SENSOR_MAKER.

Please, could you consider updating the [Argo spreadsheet](https://docs.google.com/spreadsheets/d/1Aw8B7FFUjG4e9MveD5qqvI7ZbB-z_x32IQnpHZbXVZA/edit#gid=6) with these? 

Thanks, Violetta

**Comment by mbelbeoch** [comment]
Ok thanks well noted.
But MENSOR has many products. Which one is it ?
From: Violetta Paba ***@***.***>
Sent: Tuesday, 14 September 2021 13:24
To: nvs-vocabs/R26 ***@***.***>
Cc: Belbeoch Mathieu (OceanOPS) ***@***.***>; Team mention ***@***.***>
Subject: [nvs-vocabs/R26] New entries in R26 for MENSOR and QUARTZDYNE (#2)


@nvs-vocabs/reference-tables<https://m365.eu.vadesecure.com/safeproxy/v4?f=sdjd1zmLESl84wC_137r7sj0yvBFC3C2wiFgdj3esldgg82xkeqFZDyPl-k-IeQV&i=fyMIUbLK6lpOYGmYYYTJziC28OAf2jUE-OFSKWohKgPRUo6yog-kHl6sbLcsMF69YMvW6Lvzy6aMxM41-LBxNw&k=fxYM&r=XHZd15B1EvcFDgnj3RRaN_jB9pMt5_HDL3LpP_ufsn0gqWr9mE2Vt7gb53rn6vci&s=be3da74fa3960008bff4c867578b8b503809b1a3ce9cf3d1bbb5d4d4a965af68&u=https%3A%2F%2Fgithub.com%2Forgs%2Fnvs-vocabs%2Fteams%2Freference-tables>

I have added the following codes in R26<https://m365.eu.vadesecure.com/safeproxy/v4?f=ZbNshu8RnY4JXbisvl6lxjPHIdySu9MakKfzzjGggDaRDdnR7IveZ44FFQakX3ZL&i=BFvlkkbWX5f561cOi5VcoPNBV1pUsRXClqPiCGSe-qHKibi0fEtBKiKlhab2fdYKPz-oOYF_xxH69vThs8WVUA&k=7gMw&r=vozAGKRIH03qNDVbsAf7LnJRg9Im8wbyOeGZzWrhv1eHspJSE7Oo8c8fmjtRJMin&s=928629d7ca21c169c7beaddee7cb01fa091454db54faed72e0deba9bfb047104&u=http%3A%2F%2Fvocab.nerc.ac.uk%2Fsearch_nvs%2FR26%2F%3Fsearchstr%3D%26options%3Didentifier%2Cpreflabel%2Caltlabel%2Cstatus_accepted%26rbaddfilter%3Dinc%26searchstr2%3D> (please note it takes ~24h for them to show up on the VNS).

MENSOR - A manufacturing company located in San Marcos, Texas (United States of America), specialised in precision pressure products.
QUARTZDYNE - A ChampionX company specialised in resonating quartz pressure transducers and temperature gauges, located in Salt Lake City, Utah (United States of America).

I did so in order to be able to map R27 sensor models 'MENSOR' and 'QUARTZDYNE_DSB301-10-C85' to the correct manufacturer from SENSOR_MAKER.

Please, could you consider updating the Argo spreadsheet<https://m365.eu.vadesecure.com/safeproxy/v4?f=jeVNBuJUqyiqWXT_US9rodVDAFLtaOLph_pB0b-psXLLljVdFKWVC2YPSzIryHTJ&i=c-2q0ap2TjbBu2q9128vyuxPf79JoFWbq-wdmr2H7omeOWX-5pHyP3rWZw0swjDOmggJBnNmSAzolf2kb09hgQ&k=QOXa&r=GaLvuUdWtRUe5J4A3eFM3SG207fXmLk3EaDrnuOd0Q-CiPuMx3hpQyJtc_8RVcVY&s=18831254dc7e6430b1700dd4c1c7d5e75f141f133535d50854462652c6a0314e&u=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1Aw8B7FFUjG4e9MveD5qqvI7ZbB-z_x32IQnpHZbXVZA%2Fedit%23gid%3D6> with these?

Thanks, Violetta

-
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub<https://m365.eu.vadesecure.com/safeproxy/v4?f=1QkuyUxUDRRiSxURH_Ha4qc8S_vYpwo7wxAW1ItvtUnx59o27gfgC5w1Q5R5ZUjP&i=gCNa0FmJ5Hn_9n8xXQD3EQ1fz5cQPY81pWaSqgA0MkPTFnkHnNePSGQtG-TNq7A_xJnyyjN7vILojZ1E26r3yA&k=M9A9&r=vvWBNBeGXbM6q5Ew0cjCPkSadA2ZIRbofSCN3kQieCTgJbyZPXbYarBSzBoarhOa&s=475291050134c0e805f995c3911b40330cdf9414247ecc3f9720453cd38990c3&u=https%3A%2F%2Fgithub.com%2Fnvs-vocabs%2FR26%2Fissues%2F2>, or unsubscribe<https://m365.eu.vadesecure.com/safeproxy/v4?f=yPjA6a-JxNoQEpTiqeh-Eyz8KrGyFXsq3tNBhqWqCIIVIUb9SV32V9o4xdUQu7oE&i=QWMR6VHa8D3RSMOpJQ3uroMxbCFZMdXvHc8HfEB1VbCXerhs1XSF1f2QzxgCz_e9N3gQm_iDnRcBldtozrqJjQ&k=AnyF&r=mwP_MIVeIIDpwx5GrB7p8PGQ6pUbUawQkk3lQRjNP_77SgD4dirtvCrUwAbGsUtl&s=b779fc8c16f5d8b5d3e1d32ddc8bbc56a077da0995cfe19f0ef76c5e0db801c1&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARZRQW6HUSIS7WGPD3QE2Q3UB4WFFANCNFSM5D75LZ3A>.
Triage notifications on the go with GitHub Mobile for iOS<https://m365.eu.vadesecure.com/safeproxy/v4?f=T00HnVsNHbXhaZN9WCKZq_qwXEUeIfelJQHOjeVy2GXd61tWJ_Ics1wYTeLCVUdf&i=LC6llFaVTWrcX9xAvy1q-CPdE2gWEhfVrxgvmTg-QD-ZObR9uOc0twuLuXLWQ6FpsNXxND2wMnljazWgkETdlg&k=6NYu&r=-7IvJMUdfMfVsm4LPx3PThXX2y_c6XLOteCbAQlUfLuOT5oUgSAByQfVCl8ulVPK&s=392baae07070bc9ebb43baed31e1db455a45178bf1a8b9913a488bde60673665&u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://m365.eu.vadesecure.com/safeproxy/v4?f=ip3ANTZawvgcX62xNtqeYZzgiDUD1ZCxZzZew5iLXlh4Gc1eH02SxzzPL4cPVqaj&i=HJeyPCeal6VYvMd3yWhWIDcUA7IPBT6vjh29eldGo01k6M1doLOO1bdAuLEaTYCvkmSf8ZQn75a-dHHpOGRkYA&k=K0UV&r=xQmgWWlTEGarGxZqWf7ocd1hCRb-2nirIdmQatzzDxrQVS6JzxppLT0wuNkdDd_e&s=0b4e319de2172bb4c4dc68f6487a15a02b66297cd37b8f354b86648f57dda1cb&u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

________________________________

Ce message et toutes les pi?ces jointes (ci-apr?s le "message") sont ?tablis ? l'intention exclusive de ses destinataires et sont confidentiels. Si vous recevez ce message par erreur ou s'il ne vous est pas destin?, merci de le d?truire ainsi que toute copie de votre syst?me et d'en avertir imm?diatement l'exp?diteur. Toute lecture non autoris?e, toute utilisation de ce message qui n'est pas conforme ? sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite. L'Internet ne permettant pas d'assurer l'int?grit? de ce message ?lectronique susceptible d'alt?ration, l'exp?diteur (et ses filiales) d?cline(nt) toute responsabilit? au titre de ce message dans l'hypoth?se o? il aurait ?t? modifi? ou falsifi?.

This message and any attachments (the "message") is intended solely for the intended recipient(s) and is confidential. If you receive this message in error, or are not the intended recipient(s), please delete it and any copies from your systems and immediately notify the sender. Any unauthorized view, use that does not comply with its purpose, dissemination or disclosure, either whole or partial, is prohibited. Since the internet cannot guarantee the integrity of this message which may not be reliable, the sender (and its subsidiaries) shall not be liable for the message if modified or falsified.

**Comment by vpaba** [comment]
Thanks @mbelbeoch .

Currently there is only one 'MENSOR' entry in R27: http://vocab.nerc.ac.uk/collection/R27/current/, as reflected in table 27 of the original Argo spreadsheet. I had a look in OceanOps and there seems to be only one MENSOR sensor there also.

Do you think there should be more, or more specific ones given that not much detail is known of the current one?

**Comment by tcarval** [comment]
Mensor and Quartzdyne are now registered.
The Mensor action was managed in https://github.com/nvs-vocabs/ArgoVocabs/issues/31#issuecomment-1773959275
